tumblr/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts do
    resources :comments
  end
  get '/about', to: 'pages#about'
end

tumblr/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

tumblr/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
  has_many :comments, dependent: :destroy
end

tumblr/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

tumblr/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post, only: [:create, :destroy]
  def create
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

    def comment_params
      params.require(:comment).permit(:name, :body)
    end

    def find_post
      @post = Post.find(params[:post_id])
    end
end

tumblr/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

tumblr/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def find_post
      @post = Post.find(params[:id])
    end
end

tumblr/app/helpers/comments_helper.rb
module CommentsHelper
end

tumblr/app/helpers/pages_helper.rb
module PagesHelper
end

tumblr/app/helpers/posts_helper.rb
module PostsHelper
end

tumblr/app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_title"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>
  <% if user_signed_in? %>
    <p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: 'button', data: { confirm: 'Are you sure?'} %></p>
  <% end %>
</div>

tumblr/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %> <br>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>
<% end %>

tumblr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumblr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <div id="sidebar">
      <ul>
        <li class="category"><%= link_to 'Tumblr', root_path %></li>
        <li><%= link_to 'Posts', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <hr>
      <% if !user_signed_in? %>
        <li class="sign_ins"><%= link_to 'User Sign Up', new_user_registration_path %></li>
        <li class="sign_ins"><%= link_to 'User Login', new_user_session_path %></li>
      <% end %>        
      </ul>
    </div>

    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>Post Feed</p>
        <% elsif current_page?(about_path) %>
          <p>My Site</p>
        <% else %>
          <%= link_to 'Back to Post Feed', root_path %>
        <% end %>

        <% if user_signed_in? %>        
          <div class="buttons">
            <%= link_to current_user.email, edit_user_registration_path %>
            <button class="button"><%= link_to 'Make Post', new_post_path %></button>
            <button class="button"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></button>
          </div>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: 'alert') %>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

tumblr/app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag 'profile.jpeg' %>
  </div>

  <div id="content">
    <h1>It's Mr. Stick Figure</h1>
    <p>
      Lorem ipsum dolor amet artisan heirloom beard small batch craft beer leggings pop-up. Whatever hammock iPhone actually single-origin coffee selfies kogi man braid wolf asymmetrical health goth succulents four dollar toast food truck. Distillery gluten-free live-edge fanny pack crucifix, selfies bitters put a bird on it. Tote bag schlitz brooklyn vice, beard you probably haven't heard of them squid hoodie sriracha cray roof party. VHS migas banjo, 8-bit shabby chic single-origin coffee sartorial listicle blue bottle glossier pinterest pug. </p>
    <p>
      Vexillologist you probably haven't heard of them chambray polaroid schlitz. Kickstarter listicle readymade, literally kombucha glossier neutra skateboard copper mug authentic franzen fam venmo. Dreamcatcher etsy williamsburg truffaut, pop-up bushwick VHS subway tile organic. 90's sriracha typewriter air plant roof party banh mi.
    </p>
  </div>
</div>

tumblr/app/views/posts/_form.html.erb
  <%= form_for @post do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :title %> <br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %> <br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>  

tumblr/app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Fix Post</h1>

  <%= render 'form' %>
</div>

tumblr/app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="body"><%= truncate(post.body, length: 100) %></p>
    <p class="date"><%= time_ago_in_words(post.created_at) %> ago</p>
  </div>
<% end %>

tumblr/app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>Make Something</h1>

  <%= render 'form' %>
</div>

tumblr/app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago 
    <% if user_signed_in? %>
      |
      <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} %>
    <% end %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>  

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
    <h3>Join Discussion: </h3>
    <%= render "comments/form" %>
  </div>
</div>